# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'my-book-shelf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SDWebImage'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'Then'
  pod 'ObjectMapper'

  # Pods for my-book-shelf

  target 'my-book-shelfTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'my-book-shelfUITests' do
    # Pods for testing
  end

end
